### ISSUE TITLE
Suggestion to xml and wxWidgets

### ISSUE THREAD

**Issue by horvatha4** [SickheadGames/Torsion#15]
This is maybe a "two in one" solution. The new wxWidgets have:
"
wxXmlAttribute            Represents a node attribute
wxXmlDocument     This class holds XML data/document as parsed by XML parser in the root node
wxXmlNode             Represents a node in an XML document
wxXmlResource     This is the main class for interacting with the XML-based resource system
"
classes.
We (or the Torsion) need more to handle xml files?
The "CAUTION" remark is removed from the new xml.h file in wxWidgets.

**Comment by dottools** [comment]
wxWidgets still suggests to use an outside XML library as the one implementation they're using is really meant for internal use only. Meaning they designed their XML parser for just wxWidgets' components use, and not for wxWidgets library users.

**Comment by tomspilman** [comment]
Yeah...  best option is still using TinyXML2 like I suggested in https://github.com/SickheadGames/Torsion/issues/1.
